language: node_js
node_js: '10'
script:
  - yarn lint
  - yarn build
  - yarn test-ci
cache:
  yarn: true
before_deploy:
  - cd dist/lib
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    tags: true
    branch: master
